
services:
  server:
    build: .
    image: gmail_project
    container_name: gmail_server
    command: /usr/src/mytest/build/runServer ${SERVER_PORT} ${BF_SIZE} ${HASH_COUNTS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - BF_SIZE=${BF_SIZE}
      - HASH_COUNTS=${HASH_COUNTS}

  node:
    build: .
    image: gmail_project
    container_name: gmail_node
    command: node /usr/src/mytest/src/app.js ${NODE_PORT} ${SERVER_PORT} ${SERVER_HOST}
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      - NODE_PORT=${NODE_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
    depends_on:
      - server